import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen">
          {children}
        </div>
        {typeof window !== 'undefined' && (
          <nav className="fixed top-0 right-0 m-4 space-y-2">
            {sessionStorage.getItem('menu') && (
              <ul className="space-y-1">
                {JSON.parse(sessionStorage.getItem('menu') || '[]').map((opt: string) => (
                  <li key={opt} className="text-sm text-blue-600">
                    {opt}
                  </li>
                ))}
              </ul>
            )}
            <button
              className="mt-2 px-3 py-1 bg-red-600 text-white rounded text-sm"
              onClick={() => {
                const user = JSON.parse(sessionStorage.getItem('user') || 'null');
                if (user) {
                  fetch('/api/auth/logout', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ id: user.id_usuario }),
                  });
                }
                sessionStorage.clear();
                window.location.href = '/home';
              }}
            >
              Logout
            </button>
          </nav>
        )}
      </body>
    </html>
  );
}
